import PDFDocument from "pdfkit";
import { ISecurityScan } from "../models/SecurityScan";

export const generateSecurityPdf = (
  scan: ISecurityScan,
  serverName: string,
): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers: Buffer[] = [];

      doc.on("data", buffers.push.bind(buffers));
      doc.on("end", () => {
        resolve(Buffer.concat(buffers));
      });

      // Header
      doc
        .fontSize(24)
        .font("Helvetica-Bold")
        .text("Security & Compliance Report", { align: "center" });
      doc.moveDown(0.5);

      doc
        .fontSize(12)
        .font("Helvetica")
        .text(`Server: ${serverName}`, { align: "center" })
        .text(`Date: ${scan.scannedAt.toLocaleString("en-US")}`, {
          align: "center",
        })
        .text(`Overall Score: ${scan.score}/100`, { align: "center" });

      doc.moveDown(2);

      // Issues Section
      doc
        .fontSize(16)
        .font("Helvetica-Bold")
        .fillColor("#d32f2f")
        .text("Vulnerabilities & Issues");
      doc.fillColor("black");
      doc.moveDown(0.5);

      if (scan.issues.length === 0) {
        doc
          .fontSize(12)
          .font("Helvetica")
          .text("Amazing! No security issues found.");
      } else {
        scan.issues.forEach((issue) => {
          doc
            .fontSize(12)
            .font("Helvetica-Bold")
            .fillColor(issue.severity === "high" ? "#d32f2f" : "#f57c00")
            .text(`[${issue.severity.toUpperCase()}] `)
            .font("Helvetica")
            .fillColor("black")
            .text(issue.description, { continued: false });
          doc
            .fontSize(10)
            .font("Helvetica-Oblique")
            .text(`Recommendation: ${issue.recommendation}`);
          doc.moveDown(0.5);
        });
      }

      doc.moveDown(2);

      // Passed Checks Section
      doc
        .fontSize(16)
        .font("Helvetica-Bold")
        .fillColor("#2e7d32")
        .text("Passed Checks");
      doc.fillColor("black");
      doc.moveDown(0.5);

      if (scan.passedChecks.length === 0) {
        doc
          .fontSize(12)
          .font("Helvetica")
          .text("No checks passed or list is empty.");
      } else {
        scan.passedChecks.forEach((check) => {
          doc.fontSize(12).font("Helvetica").text(`✓ ${check}`);
        });
      }

      // Footer
      doc.moveDown(4);
      doc
        .fontSize(10)
        .fillColor("gray")
        .text("Generated by Pulse Deploy Manager", { align: "center" });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};
